# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a01b8134fd220900fc9fe34234754022b7ec110546ef4f9c8787d5a3dc31c6d6ca71ead22a4147b430e85c3048d6c194f148d1a9cb161a21bb8989206e3f5bd

test:
  secret_key_base: 253929216663cd5346726c37ed2aa1ba07552381c029cfdf70e23114da9487b2ef416867f309322ecd02be9cb1d0c2e744e7bf8276ac8101a1f0eed60de54ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
